# Generated by Django 3.0.7 on 2021-02-13 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20201217_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='tags',
        ),
    ]
